# LAB 08 - Pandas

In [1]:
import pandas as pd

data = {
    "StudentID":[1,2,3,4,5,6,7,8,9,10],
    "Name":["Ayesha","Ali","Sara","Usman","Anum","Ahmed","Hira","Kamran","Mahnoor","Zain"],
    "Gender":["Female","Male","Female","Male","Female","Male","Female","Male","Female","Male"],
    "Age":[20,22,21,23,20,24,22,23,21,22],
    "Department":["CS","SE","CS","IT","CS","SE","IT","CS","SE","CS"],
    "GPA":[3.7,2.9,3.2,2.5,3.9,2.7,3.4,3.0,3.5,2.8],
    "Attendance":[85,72,95,65,90,60,80,75,88,55],
    "Quiz1":[8,5,7,6,9,4,7,6,8,5],
    "Quiz2":[9,6,8,5,10,5,8,6,9,4],
    "FinalExam":[88,70,83,68,92,63,79,72,87,60]
}

df = pd.DataFrame(data)
df

,StudentID,Name,Gender,Age,Department,GPA,Attendance,Quiz1,Quiz2,FinalExam
0,1,Ayesha,Female,20,CS,3.7,85,8,9,88
1,2,Ali,Male,22,SE,2.9,72,5,6,70
2,3,Sara,Female,21,CS,3.2,95,7,8,83
3,4,Usman,Male,23,IT,2.5,65,6,5,68
4,5,Anum,Female,20,CS,3.9,90,9,10,92
5,6,Ahmed,Male,24,SE,2.7,60,4,5,63
6,7,Hira,Female,22,IT,3.4,80,7,8,79
7,8,Kamran,Male,23,CS,3.0,75,6,6,72
8,9,Mahnoor,Female,21,SE,3.5,88,8,9,87
9,10,Zain,Male,22,CS,2.8,55,5,4,60

In [2]:
# Exploration
df.describe(), df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 10 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   StudentID   10 non-null     int64
 1   Name        10 non-null     object
 2   Gender      10 non-null     object
 3   Age         10 non-null     int64
 4   Department  10 non-null     object
 5   GPA         10 non-null     float64
 6   Attendance  10 non-null     int64
 7   Quiz1       10 non-null     int64
 8   Quiz2       10 non-null     int64
 9   FinalExam   10 non-null     int64
dtypes: float64(1), int64(6), object(3)
memory usage: 932.0+ bytes

(       StudentID        Age       GPA  Attendance      Quiz1      Quiz2  \
 count   10.00000  10.000000  10.00000   10.000000  10.000000  10.000000
 mean     5.50000  21.800000   3.16000   76.500000   6.500000   7.000000
 std      3.02765   1.316561   0.45753   13.459817   1.581139   2.054805
 min      1.00000  20.000000   2.50000   55.000000   4.000000   4.000000
 25%      3.25000  21.000000   2.82500   66.750000   5.250000   5.250000
 50%      5.50000  22.000000   3.10000   77.500000   6.500000   7.000000
 75%      7.75000  22.750000   3.47500   87.250000   7.750000   8.750000
 max     10.00000  24.000000   3.90000   95.000000   9.000000  10.000000

        FinalExam
 count  10.000000
 mean   76.200000
 std    11.153475
 min    60.000000
 25%    68.500000
 50%    75.500000
 75%    86.000000
 max    92.000000  ,
 None)

In [3]:
# Cleaning
df = df.drop_duplicates()
df = df.fillna(0)
df = df.rename(columns={"FinalExam": "Final_Exam_Score"})
df.head()

,StudentID,Name,Gender,Age,Department,GPA,Attendance,Quiz1,Quiz2,Final_Exam_Score
0,1,Ayesha,Female,20,CS,3.7,85,8,9,88
1,2,Ali,Male,22,SE,2.9,72,5,6,70
2,3,Sara,Female,21,CS,3.2,95,7,8,83
3,4,Usman,Male,23,IT,2.5,65,6,5,68
4,5,Anum,Female,20,CS,3.9,90,9,10,92

In [4]:
# Feature Engineering
def performance(gpa):
    if gpa >= 3.5:
        return "Excellent"
    elif gpa >= 3.0:
        return "Good"
    else:
        return "Needs Improvement"

df["Performance_Level"] = df["GPA"].apply(performance)
df["Total_Quiz"] = df["Quiz1"] + df["Quiz2"]
df.head()

,StudentID,Name,Gender,Age,Department,GPA,Attendance,Quiz1,Quiz2,Final_Exam_Score,Performance_Level,Total_Quiz
0,1,Ayesha,Female,20,CS,3.7,85,8,9,88,Excellent,17
1,2,Ali,Male,22,SE,2.9,72,5,6,70,Needs Improvement,11
2,3,Sara,Female,21,CS,3.2,95,7,8,83,Good,15
3,4,Usman,Male,23,IT,2.5,65,6,5,68,Needs Improvement,11
4,5,Anum,Female,20,CS,3.9,90,9,10,92,Excellent,19

In [5]:
# Sorting & Grouping
sorted_df = df.sort_values(by=["GPA","Attendance"], ascending=[False,True])
grouped = df.groupby("Department").agg({
    "GPA":"mean",
    "Attendance":"mean",
    "StudentID":"count"
}).rename(columns={"StudentID":"Student_Count"})

sorted_df, grouped

(   StudentID     Name  Gender  Age Department  GPA  Attendance  Quiz1  Quiz2  \
 4          5     Anum  Female   20         CS  3.9          90      9     10
 0          1   Ayesha  Female   20         CS  3.7          85      8      9
 8          9  Mahnoor  Female   21         SE  3.5          88      8      9
 6          7     Hira  Female   22         IT  3.4          80      7      8
 2          3     Sara  Female   21         CS  3.2          95      7      8
 7          8   Kamran    Male   23         CS  3.0          75      6      6
 1          2      Ali    Male   22         SE  2.9          72      5      6
 9         10     Zain    Male   22         CS  2.8          55      5      4
 5          6    Ahmed    Male   24         SE  2.7          60      4      5
 3          4    Usman    Male   23         IT  2.5          65      6      5

    Final_Exam_Score  Performance_Level  Total_Quiz
 4                92          Excellent          19
 0                88          Excellent          17
 8                87          Excellent          17
 6                79               Good          15
 2                83               Good          15
 7                72               Good          12
 1                70  Needs Improvement          11
 9                60  Needs Improvement           9
 5                63  Needs Improvement           9
 3                68  Needs Improvement          11  ,
                  GPA  Attendance  Student_Count
 Department
 CS          3.320000   80.000000              5
 IT          2.950000   72.500000              2
 SE          3.033333   73.333333              3)

In [6]:
# Bonus
dept_avg = df.groupby("Department")["Final_Exam_Score"].transform("mean")
above_avg = df[df["Final_Exam_Score"] > dept_avg]
above_avg[["Name","Department"]]

      Name Department
0   Ayesha         CS
2     Sara         CS
4     Anum         CS
6     Hira         IT
8  Mahnoor         SE